# Generated by Django 4.2 on 2025-05-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Campos de ambas versiones:
                ('name', models.CharField(max_length=40)),            # HEAD
                ('type', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                
                ('nombre', models.CharField(max_length=100)),         # Universidad
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('nivel', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_pokemon/')),
            ],
        ),
    ]
