# Generated by Django 4.2 on 2025-06-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
    ]
