# Generated by Django 5.2.3 on 2025-06-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='entrenador',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
