# Generated by Django 4.2 on 2025-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_remove_pokemon_nivel_alter_pokemon_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pokemon/'),
        ),
    ]
